<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<link href="1.css" rel="stylesheet" />
	</head>
	<body>
		<div class="ab">
			<p>1</p>
			<p>2</p>
			<p>3</p>
			<p>4</p>
			<p>5</p>
			<p>6</p>
			<p>7</p>
			<p>8</p>
			<p>9</p>
		</div>
		<form action="controle.php">
			<div class="boxes">
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
				<input
					type="number"
					id="dt"
					min="1"
					max="9"
					maxlength="1"
					pattern="[0-9]"
					inputmode="numeric"
				/>
			</div>
			<button type="submit" id="solveBtn">Solve Sudoku</button>
		</form>
	</body>
	<script src="index.js"></script>
</html>
